=== lonesloane/GraphXQL/src/main/graphXql/ml-schemas/graphxql/entities/person.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://graph.x.ql" xmlns:gxql="http://graph.x.ql">

    <xs:complexType name="Human">
        <xs:choice>
            <xs:element name="name" type="xs:string" minOccurs="1" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="Person">
        <xs:sequence>
            <xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1" />
            <xs:element name="name" type="xs:string" minOccurs="1" />
            <xs:element name="height" type="xs:string" minOccurs="0" />
            <xs:element name="appearsIn" type="xs:string" minOccurs="0" />
            <xs:element name="friends">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:int" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Hero">
        <xs:complexContent>
            <xs:extension base="gxql:Person">
                <xs:sequence>
                    <xs:element name="foes">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="id" type="xs:int" maxOccurs="unbounded" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Foe">
        <xs:complexContent>
            <xs:extension base="gxql:Person">
                <xs:sequence>
                    <xs:element name="accomplices">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="id" type="xs:int" maxOccurs="unbounded" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="person" type="gxql:Person">
        <xs:annotation>
            <xs:documentation>Person interface</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="hero" type="gxql:Hero">
        <xs:annotation>
            <xs:documentation>Hero object (i.e. the good guy)</xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="foe" type="gxql:Foe">
        <xs:annotation>
            <xs:documentation>Foe object (i.e. the bad guy)</xs:documentation>
        </xs:annotation>
    </xs:element>

</xs:schema>

=== lonesloane/GraphXQL/src/main/graphXql/ml-modules/root/test/suites/graphXql/person-resolver/test-data/person-2.xml
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://graph.x.ql" xmlns:gxql="http://graph.x.ql" xsi:type="gxql:Foe" xsi:schemaLocation="/graphxql/entities/person.xsd">
    <id>2</id>
    <name>Joe</name>
    <height>180</height>
    <appearsIn>Return of the Jedi</appearsIn>
    <friends>
        <id>7</id>
    </friends>
    <accomplices>
        <id>3</id>
        <id>4</id>
        <id>5</id>
    </accomplices>
</person>

=== lonesloane/GraphXQL/src/main/graphXql/ml-modules/root/test/suites/graphXql/endpoint/test-data/person-4.xml
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://graph.x.ql" xsi:type="gxql:Foe" xsi:schemaLocation="/graphxql/person.xsd">
    <name>William</name>
    <height>180</height>
    <appearsIn>Return of the Jedi</appearsIn>
    <accomplices>
        <person>
            <id>2</id>
        </person>
        <person>
            <id>3</id>
        </person>
        <person>
            <id>5</id>
        </person>
    </accomplices>
</person>

=== lonesloane/GraphXQL/src/main/graphXql/ml-modules/root/test/suites/graphXql/visitor/test-data/person-1.xml
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://graph.x.ql" xsi:type="gxql:Hero" xsi:schemaLocation="/graphxql/person.xsd">
    <name>Luke</name>
    <height>180</height>
    <appearsIn>Return of the Jedi</appearsIn>
    <friends>
        <id>6</id>
    </friends>
    <foes>
        <id>2</id>
        <id>3</id>
        <id>4</id>
        <id>5</id>
    </foes>
</person>

=== lonesloane/GraphXQL/src/main/graphXql/ml-modules/root/test/suites/graphXql/endpoint/test-data/person-1.xml
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://graph.x.ql" xmlns:gxql="http://graph.x.ql" xsi:type="gxql:Hero" xsi:schemaLocation="/graphxql/person.xsd">
    <name>Luke</name>
    <height>180</height>
    <appearsIn>Return of the Jedi</appearsIn>
    <friends>
        <person>
            <id>6</id>
        </person>
    </friends>
    <foes>
        <person>
            <id>2</id>
        </person>
        <person>
            <id>3</id>
        </person>
        <person>
            <id>4</id>
        </person>
        <person>
            <id>5</id>
        </person>
    </foes>
</person>

=== lonesloane/GraphXQL/src/main/graphXql/ml-modules/root/test/suites/graphXql/person-resolver/test-data/person-5.xml
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://graph.x.ql" xmlns:gxql="http://graph.x.ql" xsi:type="gxql:Foe" xsi:schemaLocation="/graphxql/entities/person.xsd">
    <id>5</id>
    <name>Avrel</name>
    <height>180</height>
    <appearsIn>Return of the Jedi</appearsIn>
    <accomplices>
        <id>2</id>
        <id>3</id>
        <id>4</id>
    </accomplices>
</person>

=== lonesloane/GraphXQL/src/main/graphXql/ml-modules/root/test/suites/graphXql/visitor/test-data/person-2.xml
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://graph.x.ql" xsi:type="gxql:Foe" xsi:schemaLocation="/graphxql/person.xsd">
    <name>Joe</name>
    <height>180</height>
    <appearsIn>Return of the Jedi</appearsIn>
    <friends>
        <id>7</id>
    </friends>
    <accomplices>
        <id>3</id>
        <id>4</id>
        <id>5</id>
    </accomplices>
</person>

=== lonesloane/GraphXQL/src/main/graphXql/ml-modules/root/test/suites/graphXql/visitor/test-data/person-5.xml
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://graph.x.ql" xsi:type="gxql:Foe" xsi:schemaLocation="/graphxql/person.xsd">
    <name>Avrel</name>
    <height>180</height>
    <appearsIn>Return of the Jedi</appearsIn>
    <accomplices>
        <id>2</id>
        <id>3</id>
        <id>4</id>
    </accomplices>
</person>
